apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-s3-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/klvdev/crossplane-s3-bucket.git
    targetRevision: main
    path: resources
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true