apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-s3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:klvdev/crossplane-s3-bucket.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true